# Generated by Django 3.2.8 on 2021-10-29 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippeds',
            fields=[
                ('id_snipped', models.UUIDField(default=uuid.UUID('ed4fbeb2-ae40-49d5-a391-248ef75dd60c'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.TextField()),
            ],
        ),
    ]
