# Generated by Django 3.2.8 on 2021-10-29 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippets',
            fields=[
                ('id_snippet', models.UUIDField(default=uuid.UUID('d8be2cde-316d-4c96-b276-da8ffa58cd2c'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Snippeds',
        ),
    ]
