# Generated by Django 3.2.8 on 2021-10-29 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0002_auto_20211029_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippets',
            name='id_snippet',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
